# a set of test to REST API run locally

### root
http://localhost:8080/

### version
http://localhost:8080/version

### whoami (unauthenticated)
http://localhost:8080/whoami

### whoami (admin)
http://localhost:8080/whoami
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6NDEzMjk0NDAwMCwicm9sZXMiOlsiQURNSU4iXX0.XEs2S3ST_qO67gll4F8voI4DyzUGKCzsut9et5IDeWA

### GET /admin/charging-sessions (unauthorized)
GET http://localhost:8080/admin/charging-sessions

### GET /admin/charging-sessions (admin)
GET http://localhost:8080/admin/charging-sessions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6NDEzMjk0NDAwMCwicm9sZXMiOlsiQURNSU4iXX0.XEs2S3ST_qO67gll4F8voI4DyzUGKCzsut9et5IDeWA

### GET /admin/charging-sessions (admin, from)
GET http://localhost:8080/admin/charging-sessions?from=2023-01-17
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6NDEzMjk0NDAwMCwicm9sZXMiOlsiQURNSU4iXX0.XEs2S3ST_qO67gll4F8voI4DyzUGKCzsut9et5IDeWA

### GET /admin/charging-sessions (admin, till)
GET http://localhost:8080/admin/charging-sessions?till=2023-01-16
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6NDEzMjk0NDAwMCwicm9sZXMiOlsiQURNSU4iXX0.XEs2S3ST_qO67gll4F8voI4DyzUGKCzsut9et5IDeWA

### GET /admin/charging-sessions (admin, from-till)
GET http://localhost:8080/admin/charging-sessions?from=2023-01-16&till=2023-01-16
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6NDEzMjk0NDAwMCwicm9sZXMiOlsiQURNSU4iXX0.XEs2S3ST_qO67gll4F8voI4DyzUGKCzsut9et5IDeWA

### POST /admin/charge-points/${charge point id}/connectors (admin, invalid id)
POST http://localhost:8080/admin/charge-points/INVALID/connectors
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6NDEzMjk0NDAwMCwicm9sZXMiOlsiQURNSU4iXX0.XEs2S3ST_qO67gll4F8voI4DyzUGKCzsut9et5IDeWA

### POST /admin/charge-points/${charge point id}/connectors (admin)
POST http://localhost:8080/admin/charge-points/test_charge_point/connectors
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6NDEzMjk0NDAwMCwicm9sZXMiOlsiQURNSU4iXX0.XEs2S3ST_qO67gll4F8voI4DyzUGKCzsut9et5IDeWA
