# a set of test to REST API run locally

### root
http://localhost:8080/

### version
http://localhost:8080/version

### whoami (unauthorized)
http://localhost:8080/whoami

### whoami (admin)
http://localhost:8080/whoami
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6NDEzMjk0NDAwMCwicm9sZXMiOlsiQURNSU4iXX0.XEs2S3ST_qO67gll4F8voI4DyzUGKCzsut9et5IDeWA
